networks:
  production:

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - production
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  # STRAPI CMS
  backend:
    image: ${DOCKERHUB_USERNAME}/backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend/public/uploads:/opt/app/public/uploads
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: ${POSTGRES_PORT}
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    networks:
      - production
    # в docker-compose.yml в секции backend:
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "fetch('http://localhost:1337/_health').then(r => r.ok ? process.exit(0) : process.exit(1))",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # NEXT.JS FRONTEND
  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_BACKEND_URL=https://taes.com.ua
        - NEXT_PUBLIC_API_URL=https://taes.com.ua/api
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - production

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
      - ${NGINX_SSL_PORT}:${NGINX_SSL_PORT}
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./backend/public/uploads:/var/www/uploads:ro
    depends_on:
      - frontend
      - backend
    networks:
      - production

volumes:
  pgdata:
